### ISSUE TITLE
Any item can be crafted into a Tiny Pile of Blaze Powder

### ISSUE THREAD

**Issue by Windspren** [Voxel-Friend/RusticThaumaturgy#11]
Any item, when placed in the crafting grid, will be crafted into a tiny pile of blaze powder

Screenshot:
https://gyazo.com/2ba1e2610b123afad83006d45e333afc

Mods Loaded:
Baubles
Thaumcraft
Rustic
JEI
RusticThaumaturgy
ThaumicJEI

How to reproduce the bug:

1. Put an item in the crafting grid
2. Observe

**Comment by wamc2017** [comment]
Which version of RusticThaumaturgy are you using?

**Comment by Voxel-Friend** [comment]
Yes, this bug is not present with latest version. Please update.
