### ISSUE TITLE
Crusher Recipes for New Plants Not Working

### ISSUE THREAD

**Issue by Windspren** [Voxel-Friend/RusticThaumaturgy#12]
The crushing tub recipes for the plants added by this mod do not work.

I also noticed that JEI does not register the recipes, as it shows a blank item instead of the plants

Mods used are the same as last time

How to reproduce the bug:
1. Put any of the new plants in the crushing tub
2. Jump on it
3. Observe that nothing happens

**Comment by Voxel-Friend** [comment]
This bug was fixed. Use Version 2.2
