### ISSUE TITLE
[1.12.2] [2.2] Aspects

### ISSUE THREAD

**Issue by wamc2017** [Voxel-Friend/RusticThaumaturgy#13]
Hi,

not really a big issue, but the tiny pile of blaze dust, the cindermote, the shimmerpetal and the viscap are missing aspects.
Also the seeds/spores/bulb need some rebalance I guess, all got 99 metallum and 60 aqua for an instance, because of their crafting ingredients.

Thanks for looking into it.

Best regards,
wamc

**Comment by Voxel-Friend** [comment]
Oh wow, that's definitely unintentional.
I'll look into it. Thanks!

**Comment by Voxel-Friend** [comment]
Ok, I am keeping most of the seeds/bulb/spores aspects the same, minus the void, water, and metal aspects added by the metal buckets. As for the rest, how does this sound:
1. Cindermote
* 5 Fire
* 2 Plant
* 2 Aura

2. Shimmerpetal
* 5 Aura
* 2 Plant
* 2 Energy (Potentia)

3. Viscap
* 1 Plant
* 1 Death (Mortus)
* 1 Entropy

4. Tiny Pile of Blaze Dust
* 1 Alchemy
* 1 Fire

I Tried to keep them similar to the larger variants.

**Comment by wamc2017** [comment]
Hmm, one cinderpearl is worth 10 ignis and it produces 1 blaze powder (5 ignis). So maybe The cindermote should have 2 ignis (the double of the tiny pile). All other values are fine I guess. :+1:

**Comment by Voxel-Friend** [comment]
Sounds good. I'll make the change.
