### ISSUE TITLE
Issue with Fluid Registry

### ISSUE THREAD

**Issue by Voxel-Friend** [Voxel-Friend/RusticThaumaturgy#4]
Crashlog: https://pastebin.com/6paHLPsZ
Ugh. I'm stumped. Any ideas?

**Comment by Lordician** [comment]
As said in the discord:
It seems you do not actually register the fluid in the fluid registery.
At your register function in Modfluids (around line 268) add:
FluidRegistry.registerFluid(fluid);
as the first line in the function.

**Comment by Voxel-Friend** [comment]
Tried that, now crashes like this: https://pastebin.com/qivdTvRb
