### ISSUE TITLE
[1.12.2] [v2.0-beta2] Research issues

### ISSUE THREAD

**Issue by wamc2017** [Voxel-Friend/RusticThaumaturgy#5]
Hi,

1 . The base research doesn't complete, I guess AUTOUNLOCK doesn't work if a research got multiple stages.
2. The text for the Viscap stage 1 shows research.RT_VISCAP_SPORES.stage.1 instead of the text, according to the lang file it should be research.RT_VISCAP.stage.1 I guess... (seems to have the same issue with stage 2)

Thanks for looking into it.

Best regards
wamc

**Comment by Voxel-Friend** [comment]
Thanks! Will fix.
