### ISSUE TITLE
[1.12.2] [v2.0-beta2] Recipe issues

### ISSUE THREAD

**Issue by wamc2017** [Voxel-Friend/RusticThaumaturgy#6]
Hi,

it seems the recipes to create tiny piles of blaze dust/quicksilver drops and the wort recipes for cindermote/shimmerpetal/viscap are missing their input. I also can't find an option to create the spores/seeds/bulb (but I guess the infusion recipes are NYI?)

Thanks for looking into it.

Best regards,
wamc

Edit: The wort recipes are fixed with beta 3, so I guess ModBlocksRT should be ModItemsRT in those two lines too...

https://github.com/Voxel-Friend/RusticThaumaturgy/blob/83c1bd4ff47278812da9af438c13cb45de13a519/src/main/java/com/github/voxelfriend/rusticthaumaturgy/crafting/Recipes.java#L110-L111

**Comment by Voxel-Friend** [comment]
Thanks for the heads up! Will be fixed asap.

**Comment by wamc2017** [comment]
@Voxel-Friend,

I guess I found the issue why the Infusion recipes are not working.

For instance: 
https://github.com/Voxel-Friend/RusticThaumaturgy/blob/7d01d5cdf57fc82fa0bd36ff680a90ad6dfebfb9/src/main/java/com/github/voxelfriend/rusticthaumaturgy/core/CommonProxy.java#L69

should be

`new InfusionRecipe("RT_CINDERMOTE",`

`
