### ISSUE TITLE
2.0 beta 1, 2 and 3 are both crashing the server on load.

### ISSUE THREAD

**Issue by ProsperCraft** [Voxel-Friend/RusticThaumaturgy#7]
https://gist.github.com/ProsperCraft/7706b0a984ae9be422f42b169a03f05f

The client seems fine with it.

I had to roll back my Ancient TownCraft pack to 1.2

**Comment by Voxel-Friend** [comment]
Ok, could you please supply me with the full log file?

**Comment by ProsperCraft** [comment]
[logs.zip](https://github.com/Voxel-Friend/RusticThaumaturgy/files/2363918/logs.zip)

**Comment by Voxel-Friend** [comment]
I am sorry, it would seem that this is not on my end. The log file mentions discord integration as a possible culprit. Try them.

**Comment by Voxel-Friend** [comment]
```[19:10:45] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up all world data: 0 data blobs
[19:10:45] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from DiscordIntegration (discordintegration)
[19:10:45] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException```

**Comment by ProsperCraft** [comment]
But why does it happen only with your new update?

We have been running Rustic Thaumaturgy-1.2.jar  without any problems at all.

**Comment by erindalc** [comment]
I do not have discord integration and I'm also having a dedicated server crash

**Comment by erindalc** [comment]
Log: https://gist.github.com/erindalc/73d29346c23650c1d7f1dbbcb33ad4a3

**Comment by Voxel-Friend** [comment]
Can either of you try and recreate the crash with as little mods as possible?

**Comment by erindalc** [comment]
Happens with minimum mod list:
https://gist.github.com/erindalc/43f4b9df5d628f8786232f4ce3f38c72

**Comment by Voxel-Friend** [comment]
There is honestly very little for me to go off of here, as "It crashes when I add your mod" is vague, and the logs don't necessarily point to my mod itself.

**Comment by Voxel-Friend** [comment]
Could you please supply the full log file?

**Comment by erindalc** [comment]
debug log: https://gist.github.com/erindalc/09907145cb023c5e4bfc40d92ce9865e
latest log: https://gist.github.com/erindalc/dcab443e13af2af0aee0105bac781eb4

**Comment by Voxel-Friend** [comment]
Alright. I shall put some time into this when I can, I can't promise it will be fixed within the week.

**Comment by ProsperCraft** [comment]
2.1 still crashes the server.

**Comment by Voxel-Friend** [comment]
Ok, please try out this test build to see if the crash still occurs (Tried on test sever locally and found no problems).
[Rustic Thaumaturgy-2.1.1.jar.zip](https://github.com/Voxel-Friend/RusticThaumaturgy/files/2366042/Rustic.Thaumaturgy-2.1.1.jar.zip)

**Comment by Voxel-Friend** [comment]
Well, I have had no problems running my test server with a few testers, so I will go ahead and release the update. Thanks for being patient!

**Comment by erindalc** [comment]
Works good for me.
